baseurl = "https://blog.matiaspan.dev"
languageCode = "en-us"
Title = "Matias Pan"
theme = "hugo_theme_pickles"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "matiaspan26"
  github = "matipan"
  gitlab = "matipan"
  linkedin = "Your LinkedIn username"
  author = "Matias Pan"
  authorwebsite = "blog.matiaspan.dev"
  avatar = "/images/profile.jpeg"
  contact = "mailto:matias.pan26@gmail.com)"
  bio = "Test"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Blog"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
